sudo: required
language: bash
services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

env:
  global:
    - VERSION=3.3.0-alpine IMAGE=opencv BASEOS_VER=alpine:3.5 APP_VER=3.3.0
    
jobs:
  include:
    - stage: build, test and deploy image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build --build-arg BASEOS_VER=$BASEOS_VER --build-arg APP_VER=$APP_VER -t $DOCKER_USERNAME/$IMAGE:latest -t $DOCKER_USERNAME/$IMAGE:$VERSION $VERSION
      - docker images
      - docker run --rm $DOCKER_USERNAME/$IMAGE sh "/root/unit-test.sh"
      - docker tag $DOCKER_USERNAME/$IMAGE:latest $DOCKER_USERNAME/$IMAGE:$VERSION
      - docker push $DOCKER_USERNAME/$IMAGE:latest
      - docker push $DOCKER_USERNAME/$IMAGE:$VERSION
